# ---- git
alias gap="git add --patch"
alias gb="git branch"
alias gc="git commit"
alias gcf="f() { git commit --fixup=$1 };f"
alias gcm="git commit --amend"
alias gcmn="git commit --amend --no-edit"
alias gco="git checkout"
alias gd="git diff"
alias gdc="git diff --cached"
alias gl="git log --stat"
alias glo="git log --pretty=format:'%C(yellow)%h %Cred%ad %Cgreen%d %Creset%s' --date=short --abbrev=7"
alias gp="git pull"
alias gpf="git push --force-with-lease origin @"
alias gpo="git push origin @"
alias gr="git rebase"
alias gs="git status"
alias gsh="git show"
alias gul="git reset --soft @~ && git restore --staged ."
alias gum="branch=\$(git symbolic-ref --short refs/remotes/origin/HEAD | sed 's@^origin/@@'); git checkout \$branch && git pull && git checkout - && git rebase \$branch"
